# Generated by Django 5.1.4 on 2024-12-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='fertilizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='location',
            field=models.CharField(default='Desconhecido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvest',
            name='quantity_in_tons',
            field=models.DecimalField(decimal_places=2, default='Não informada', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvest',
            name='seed_type',
            field=models.CharField(default='Não informada', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harvest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
