# Generated by Django 5.1.4 on 2024-12-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_harvest_fertilizer_harvest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='fertilizer',
            field=models.CharField(blank=True, default='Não informada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='location',
            field=models.CharField(default='Desconhecido', max_length=255),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity_in_tons',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
