# Generated by Django 5.1.4 on 2024-12-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_alter_harvest_fertilizer_alter_harvest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='quantity_in_tons',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
