# Generated by Django 5.1.4 on 2024-12-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_alter_harvest_quantity_in_tons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='quantity_in_tons',
            field=models.CharField(blank=True, default='Não informada', max_length=255),
        ),
    ]
